#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TestFragment.Droid.Resource", IsApplication=true)]

namespace TestFragment.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			ViewPagerIndicator.Droid.Resource.Attribute.centered = TestFragment.Droid.Resource.Attribute.centered;
			ViewPagerIndicator.Droid.Resource.Attribute.clipPadding = TestFragment.Droid.Resource.Attribute.clipPadding;
			ViewPagerIndicator.Droid.Resource.Attribute.fillColor = TestFragment.Droid.Resource.Attribute.fillColor;
			ViewPagerIndicator.Droid.Resource.Attribute.footerColor = TestFragment.Droid.Resource.Attribute.footerColor;
			ViewPagerIndicator.Droid.Resource.Attribute.footerIndicatorHeight = TestFragment.Droid.Resource.Attribute.footerIndicatorHeight;
			ViewPagerIndicator.Droid.Resource.Attribute.footerIndicatorStyle = TestFragment.Droid.Resource.Attribute.footerIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Attribute.footerIndicatorUnderlinePadding = TestFragment.Droid.Resource.Attribute.footerIndicatorUnderlinePadding;
			ViewPagerIndicator.Droid.Resource.Attribute.footerLineHeight = TestFragment.Droid.Resource.Attribute.footerLineHeight;
			ViewPagerIndicator.Droid.Resource.Attribute.footerPadding = TestFragment.Droid.Resource.Attribute.footerPadding;
			ViewPagerIndicator.Droid.Resource.Attribute.orientation = TestFragment.Droid.Resource.Attribute.orientation;
			ViewPagerIndicator.Droid.Resource.Attribute.pageColor = TestFragment.Droid.Resource.Attribute.pageColor;
			ViewPagerIndicator.Droid.Resource.Attribute.radius = TestFragment.Droid.Resource.Attribute.radius;
			ViewPagerIndicator.Droid.Resource.Attribute.selectedBold = TestFragment.Droid.Resource.Attribute.selectedBold;
			ViewPagerIndicator.Droid.Resource.Attribute.selectedColor = TestFragment.Droid.Resource.Attribute.selectedColor;
			ViewPagerIndicator.Droid.Resource.Attribute.snap = TestFragment.Droid.Resource.Attribute.snap;
			ViewPagerIndicator.Droid.Resource.Attribute.strokeColor = TestFragment.Droid.Resource.Attribute.strokeColor;
			ViewPagerIndicator.Droid.Resource.Attribute.strokeWidth = TestFragment.Droid.Resource.Attribute.strokeWidth;
			ViewPagerIndicator.Droid.Resource.Attribute.textColor = TestFragment.Droid.Resource.Attribute.textColor;
			ViewPagerIndicator.Droid.Resource.Attribute.textSize = TestFragment.Droid.Resource.Attribute.textSize;
			ViewPagerIndicator.Droid.Resource.Attribute.titlePadding = TestFragment.Droid.Resource.Attribute.titlePadding;
			ViewPagerIndicator.Droid.Resource.Attribute.topPadding = TestFragment.Droid.Resource.Attribute.topPadding;
			ViewPagerIndicator.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle = TestFragment.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Attribute.vpiTabPageIndicatorStyle = TestFragment.Droid.Resource.Attribute.vpiTabPageIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Attribute.vpiTabTextStyle = TestFragment.Droid.Resource.Attribute.vpiTabTextStyle;
			ViewPagerIndicator.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle = TestFragment.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Boolean.default_circle_indicator_centered = TestFragment.Droid.Resource.Boolean.default_circle_indicator_centered;
			ViewPagerIndicator.Droid.Resource.Boolean.default_circle_indicator_snap = TestFragment.Droid.Resource.Boolean.default_circle_indicator_snap;
			ViewPagerIndicator.Droid.Resource.Boolean.default_title_indicator_selected_bold = TestFragment.Droid.Resource.Boolean.default_title_indicator_selected_bold;
			ViewPagerIndicator.Droid.Resource.Color.default_circle_indicator_fill_color = TestFragment.Droid.Resource.Color.default_circle_indicator_fill_color;
			ViewPagerIndicator.Droid.Resource.Color.default_circle_indicator_page_color = TestFragment.Droid.Resource.Color.default_circle_indicator_page_color;
			ViewPagerIndicator.Droid.Resource.Color.default_circle_indicator_stroke_color = TestFragment.Droid.Resource.Color.default_circle_indicator_stroke_color;
			ViewPagerIndicator.Droid.Resource.Color.default_title_indicator_footer_color = TestFragment.Droid.Resource.Color.default_title_indicator_footer_color;
			ViewPagerIndicator.Droid.Resource.Color.default_title_indicator_selected_color = TestFragment.Droid.Resource.Color.default_title_indicator_selected_color;
			ViewPagerIndicator.Droid.Resource.Color.default_title_indicator_text_color = TestFragment.Droid.Resource.Color.default_title_indicator_text_color;
			ViewPagerIndicator.Droid.Resource.Color.vpi__background_holo_dark = TestFragment.Droid.Resource.Color.vpi__background_holo_dark;
			ViewPagerIndicator.Droid.Resource.Color.vpi__background_holo_light = TestFragment.Droid.Resource.Color.vpi__background_holo_light;
			ViewPagerIndicator.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark = TestFragment.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			ViewPagerIndicator.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light = TestFragment.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			ViewPagerIndicator.Droid.Resource.Color.vpi__bright_foreground_holo_dark = TestFragment.Droid.Resource.Color.vpi__bright_foreground_holo_dark;
			ViewPagerIndicator.Droid.Resource.Color.vpi__bright_foreground_holo_light = TestFragment.Droid.Resource.Color.vpi__bright_foreground_holo_light;
			ViewPagerIndicator.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark = TestFragment.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			ViewPagerIndicator.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light = TestFragment.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			ViewPagerIndicator.Droid.Resource.Color.vpi__dark_theme = TestFragment.Droid.Resource.Color.vpi__dark_theme;
			ViewPagerIndicator.Droid.Resource.Color.vpi__light_theme = TestFragment.Droid.Resource.Color.vpi__light_theme;
			ViewPagerIndicator.Droid.Resource.Dimension.default_circle_indicator_radius = TestFragment.Droid.Resource.Dimension.default_circle_indicator_radius;
			ViewPagerIndicator.Droid.Resource.Dimension.default_circle_indicator_stroke_width = TestFragment.Droid.Resource.Dimension.default_circle_indicator_stroke_width;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_clip_padding = TestFragment.Droid.Resource.Dimension.default_title_indicator_clip_padding;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height = TestFragment.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = TestFragment.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_footer_line_height = TestFragment.Droid.Resource.Dimension.default_title_indicator_footer_line_height;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_footer_padding = TestFragment.Droid.Resource.Dimension.default_title_indicator_footer_padding;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_text_size = TestFragment.Droid.Resource.Dimension.default_title_indicator_text_size;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_title_padding = TestFragment.Droid.Resource.Dimension.default_title_indicator_title_padding;
			ViewPagerIndicator.Droid.Resource.Dimension.default_title_indicator_top_padding = TestFragment.Droid.Resource.Dimension.default_title_indicator_top_padding;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator = TestFragment.Droid.Resource.Drawable.custom_tab_indicator;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_focused = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_focused;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_selected = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_selected;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_selected_focused = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_selected_focused;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_selected_pressed = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_selected_pressed;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_unselected = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_unselected;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_unselected_focused = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_unselected_focused;
			ViewPagerIndicator.Droid.Resource.Drawable.custom_tab_indicator_unselected_pressed = TestFragment.Droid.Resource.Drawable.custom_tab_indicator_unselected_pressed;
			ViewPagerIndicator.Droid.Resource.Drawable.icon = TestFragment.Droid.Resource.Drawable.icon;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_indicator = TestFragment.Droid.Resource.Drawable.vpi__tab_indicator;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_selected_focused_holo = TestFragment.Droid.Resource.Drawable.vpi__tab_selected_focused_holo;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_selected_holo = TestFragment.Droid.Resource.Drawable.vpi__tab_selected_holo;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo = TestFragment.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo = TestFragment.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_unselected_holo = TestFragment.Droid.Resource.Drawable.vpi__tab_unselected_holo;
			ViewPagerIndicator.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo = TestFragment.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			ViewPagerIndicator.Droid.Resource.Id.horizontal = TestFragment.Droid.Resource.Id.horizontal;
			ViewPagerIndicator.Droid.Resource.Id.none = TestFragment.Droid.Resource.Id.none;
			ViewPagerIndicator.Droid.Resource.Id.triangle = TestFragment.Droid.Resource.Id.triangle;
			ViewPagerIndicator.Droid.Resource.Id.underline = TestFragment.Droid.Resource.Id.underline;
			ViewPagerIndicator.Droid.Resource.Id.vertical = TestFragment.Droid.Resource.Id.vertical;
			ViewPagerIndicator.Droid.Resource.Integer.default_circle_indicator_orientation = TestFragment.Droid.Resource.Integer.default_circle_indicator_orientation;
			ViewPagerIndicator.Droid.Resource.Integer.default_title_indicator_footer_indicator_style = TestFragment.Droid.Resource.Integer.default_title_indicator_footer_indicator_style;
			ViewPagerIndicator.Droid.Resource.Layout.vpi__tab = TestFragment.Droid.Resource.Layout.vpi__tab;
			ViewPagerIndicator.Droid.Resource.Style.CustomCirclePageIndicator = TestFragment.Droid.Resource.Style.CustomCirclePageIndicator;
			ViewPagerIndicator.Droid.Resource.Style.CustomTabPageIndicator = TestFragment.Droid.Resource.Style.CustomTabPageIndicator;
			ViewPagerIndicator.Droid.Resource.Style.CustomTabPageIndicator_Text = TestFragment.Droid.Resource.Style.CustomTabPageIndicator_Text;
			ViewPagerIndicator.Droid.Resource.Style.CustomTitlePageIndicator = TestFragment.Droid.Resource.Style.CustomTitlePageIndicator;
			ViewPagerIndicator.Droid.Resource.Style.StyledIndicators = TestFragment.Droid.Resource.Style.StyledIndicators;
			ViewPagerIndicator.Droid.Resource.Style.TextAppearance_TabPageIndicator = TestFragment.Droid.Resource.Style.TextAppearance_TabPageIndicator;
			ViewPagerIndicator.Droid.Resource.Style.Theme_PageIndicatorDefaults = TestFragment.Droid.Resource.Style.Theme_PageIndicatorDefaults;
			ViewPagerIndicator.Droid.Resource.Style.Widget = TestFragment.Droid.Resource.Style.Widget;
			ViewPagerIndicator.Droid.Resource.Style.Widget_CirclePageIndicator = TestFragment.Droid.Resource.Style.Widget_CirclePageIndicator;
			ViewPagerIndicator.Droid.Resource.Style.Widget_TabPageIndicator = TestFragment.Droid.Resource.Style.Widget_TabPageIndicator;
			ViewPagerIndicator.Droid.Resource.Style.Widget_TabPageIndicator_Text = TestFragment.Droid.Resource.Style.Widget_TabPageIndicator_Text;
			ViewPagerIndicator.Droid.Resource.Style.Widget_TitlePageIndicator = TestFragment.Droid.Resource.Style.Widget_TitlePageIndicator;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator = TestFragment.Droid.Resource.Styleable.CirclePageIndicator;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_centered = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_centered;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_fillColor = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_fillColor;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_orientation = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_orientation;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_pageColor = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_pageColor;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_radius = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_radius;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_snap = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_snap;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_strokeColor = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_strokeColor;
			ViewPagerIndicator.Droid.Resource.Styleable.CirclePageIndicator_strokeWidth = TestFragment.Droid.Resource.Styleable.CirclePageIndicator_strokeWidth;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator = TestFragment.Droid.Resource.Styleable.TitlePageIndicator;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_clipPadding = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_clipPadding;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_footerColor = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_footerColor;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_footerLineHeight = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_footerPadding = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_footerPadding;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_selectedBold = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_selectedBold;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_selectedColor = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_selectedColor;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_textColor = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_textColor;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_textSize = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_textSize;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_titlePadding = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_titlePadding;
			ViewPagerIndicator.Droid.Resource.Styleable.TitlePageIndicator_topPadding = TestFragment.Droid.Resource.Styleable.TitlePageIndicator_topPadding;
			ViewPagerIndicator.Droid.Resource.Styleable.ViewPagerIndicator = TestFragment.Droid.Resource.Styleable.ViewPagerIndicator;
			ViewPagerIndicator.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = TestFragment.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = TestFragment.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			ViewPagerIndicator.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabTextStyle = TestFragment.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabTextStyle;
			ViewPagerIndicator.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = TestFragment.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010019
			public const int MvxBind = 2130771993;
			
			// aapt resource value: 0x7f01001c
			public const int MvxDropDownItemTemplate = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int MvxItemTemplate = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int MvxLang = 2130771994;
			
			// aapt resource value: 0x7f01001d
			public const int MvxSource = 2130771997;
			
			// aapt resource value: 0x7f010004
			public const int centered = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int clipPadding = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int fillColor = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int footerColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorHeight = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int footerIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int footerIndicatorUnderlinePadding = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int footerLineHeight = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int footerPadding = 2130771986;
			
			// aapt resource value: 0x7f010007
			public const int orientation = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int pageColor = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int radius = 2130771976;
			
			// aapt resource value: 0x7f010014
			public const int selectedBold = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int selectedColor = 2130771987;
			
			// aapt resource value: 0x7f010009
			public const int snap = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int strokeColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int strokeWidth = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int textColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int textSize = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int titlePadding = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int topPadding = 2130771992;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int vpiTabPageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int vpiTabTextStyle = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int vpiTitlePageIndicatorStyle = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_centered = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_snap = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_title_indicator_selected_bold = 2131165186;
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int default_circle_indicator_fill_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int default_circle_indicator_page_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int default_circle_indicator_stroke_color = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int default_title_indicator_footer_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int default_title_indicator_selected_color = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int default_title_indicator_text_color = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int vpi__background_holo_dark = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int vpi__background_holo_light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int vpi__bright_foreground_disabled_holo_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int vpi__bright_foreground_holo_dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int vpi__bright_foreground_holo_light = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int vpi__bright_foreground_inverse_holo_light = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int vpi__dark_theme = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int vpi__light_theme = 2131099663;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_stroke_width = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int default_title_indicator_clip_padding = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int default_title_indicator_footer_indicator_height = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int default_title_indicator_footer_indicator_underline_padding = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int default_title_indicator_footer_line_height = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int default_title_indicator_footer_padding = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int default_title_indicator_text_size = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int default_title_indicator_title_padding = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int default_title_indicator_top_padding = 2131296265;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int custom_tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_tab_indicator_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custom_tab_indicator_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_tab_indicator_selected_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_tab_indicator_selected_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int custom_tab_indicator_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int custom_tab_indicator_unselected_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_tab_indicator_unselected_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int vpi__tab_indicator = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int vpi__tab_selected_focused_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int vpi__tab_selected_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vpi__tab_selected_pressed_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int vpi__tab_unselected_focused_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int vpi__tab_unselected_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int vpi__tab_unselected_pressed_holo = 2130837519;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int MvxBindingTagUnique = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int horizontal = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int indicator = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int none = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int pager = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int triangle = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int underline = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int vertical = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_orientation = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_title_indicator_footer_indicator_style = 2131230721;
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Page1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Page2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page3 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int vpi__tab = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0001
			public const int ApplicationName = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int Hello = 2131361792;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040002
			public const int CustomCirclePageIndicator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CustomTabPageIndicator = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int CustomTabPageIndicator_Text = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int CustomTitlePageIndicator = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int StyledIndicators = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int TextAppearance_TabPageIndicator = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int Theme_PageIndicatorDefaults = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Widget = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Widget_CirclePageIndicator = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int Widget_TabPageIndicator = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Widget_TabPageIndicator_Text = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int Widget_TitlePageIndicator = 2130968584;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] MvxBinding = new int[] {
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[] {
					2130771997};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771995,
					2130771996};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] TitlePageIndicator = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabTextStyle = 3;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
