#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ViewPagerIndicator.Resource", IsApplication=true)]

namespace ViewPagerIndicator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int centered = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int clipPadding = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int fillColor = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int footerColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorHeight = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int footerIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int footerIndicatorUnderlinePadding = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int footerLineHeight = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int footerPadding = 2130771986;
			
			// aapt resource value: 0x7f010007
			public const int orientation = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int pageColor = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int radius = 2130771976;
			
			// aapt resource value: 0x7f010014
			public const int selectedBold = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int selectedColor = 2130771987;
			
			// aapt resource value: 0x7f010009
			public const int snap = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int strokeColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int strokeWidth = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int textColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int textSize = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int titlePadding = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int topPadding = 2130771992;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int vpiTabPageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int vpiTabTextStyle = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int vpiTitlePageIndicatorStyle = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_centered = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_snap = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_title_indicator_selected_bold = 2131230722;
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int default_circle_indicator_fill_color = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int default_circle_indicator_page_color = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int default_circle_indicator_stroke_color = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int default_title_indicator_footer_color = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int default_title_indicator_selected_color = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int default_title_indicator_text_color = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int vpi__background_holo_dark = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int vpi__background_holo_light = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int vpi__bright_foreground_disabled_holo_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int vpi__bright_foreground_holo_dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int vpi__bright_foreground_holo_light = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int vpi__bright_foreground_inverse_holo_light = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int vpi__dark_theme = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int vpi__light_theme = 2131165199;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public const int default_circle_indicator_radius = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int default_circle_indicator_stroke_width = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int default_title_indicator_clip_padding = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int default_title_indicator_footer_indicator_height = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int default_title_indicator_footer_indicator_underline_padding = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int default_title_indicator_footer_line_height = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int default_title_indicator_footer_padding = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int default_title_indicator_text_size = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int default_title_indicator_title_padding = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int default_title_indicator_top_padding = 2131361801;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int custom_tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_tab_indicator_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custom_tab_indicator_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_tab_indicator_selected_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_tab_indicator_selected_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int custom_tab_indicator_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int custom_tab_indicator_unselected_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_tab_indicator_unselected_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int vpi__tab_indicator = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int vpi__tab_selected_focused_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int vpi__tab_selected_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vpi__tab_selected_pressed_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int vpi__tab_unselected_focused_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int vpi__tab_unselected_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int vpi__tab_unselected_pressed_holo = 2130837519;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int add_page = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int horizontal = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int indicator = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int none = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int pager = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int random = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int remove_page = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int triangle = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int underline = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int vertical = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_orientation = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_title_indicator_footer_indicator_style = 2131296257;
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int simple_circles = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int simple_circles_vertical = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int simple_tabs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int simple_titles = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int themed_circles = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int themed_titles = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int vpi__tab = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menu = 2131427328;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int CustomCirclePageIndicator = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int CustomTabPageIndicator = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int CustomTabPageIndicator_Text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int CustomTitlePageIndicator = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int StyledIndicators = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int TextAppearance_TabPageIndicator = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int Theme_PageIndicatorDefaults = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Widget = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Widget_CirclePageIndicator = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int Widget_TabPageIndicator = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Widget_TabPageIndicator_Text = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int Widget_TitlePageIndicator = 2131034120;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] TitlePageIndicator = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabTextStyle = 3;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
